// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9GZ01j3epePxOkuXl-IgUK1Oyr8YldHo',
    appId: '1:93004000116:web:b6539696690eea531f5a21',
    messagingSenderId: '93004000116',
    projectId: 'rexz-377c6',
    authDomain: 'rexz-377c6.firebaseapp.com',
    storageBucket: 'rexz-377c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9OdEgT8aHBRqE_Hw5iIRqbbuICMnKQ3g',
    appId: '1:93004000116:android:14c478e08ba8c0c41f5a21',
    messagingSenderId: '93004000116',
    projectId: 'rexz-377c6',
    storageBucket: 'rexz-377c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ZFEwMPJ1I1pDM9MgvDLO0WbY6pMhXQ8',
    appId: '1:93004000116:ios:af6e94ac562fe2fa1f5a21',
    messagingSenderId: '93004000116',
    projectId: 'rexz-377c6',
    storageBucket: 'rexz-377c6.appspot.com',
    androidClientId: '93004000116-2tkkil838c6ipb3m5uaoi2r5jk9f0hm5.apps.googleusercontent.com',
    iosClientId: '93004000116-h1hdh3kbsjttsvapsldnjk9ohjv8tvib.apps.googleusercontent.com',
    iosBundleId: 'com.example.rexParts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ZFEwMPJ1I1pDM9MgvDLO0WbY6pMhXQ8',
    appId: '1:93004000116:ios:af6e94ac562fe2fa1f5a21',
    messagingSenderId: '93004000116',
    projectId: 'rexz-377c6',
    storageBucket: 'rexz-377c6.appspot.com',
    androidClientId: '93004000116-2tkkil838c6ipb3m5uaoi2r5jk9f0hm5.apps.googleusercontent.com',
    iosClientId: '93004000116-h1hdh3kbsjttsvapsldnjk9ohjv8tvib.apps.googleusercontent.com',
    iosBundleId: 'com.example.rexParts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9GZ01j3epePxOkuXl-IgUK1Oyr8YldHo',
    appId: '1:93004000116:web:2a97a0712fc83e3f1f5a21',
    messagingSenderId: '93004000116',
    projectId: 'rexz-377c6',
    authDomain: 'rexz-377c6.firebaseapp.com',
    storageBucket: 'rexz-377c6.appspot.com',
  );
}
